
export const SELECT_INGREDIENT = 'data::SELECT_INGREDIENT';

export const FETCH_INGREDIENTS_ATTEMPT = 'data::FETCH_INGREDIENTS_ATTEMPT';
export const FETCH_INGREDIENTS_SUCCESS = 'data::FETCH_INGREDIENTS_SUCCESS';
export const FETCH_INGREDIENTS_FAILED = 'data::FETCH_INGREDIENTS_FAILED';

export const FETCH_RECIPES_ATTEMPT = 'data::FETCH_RECIPES_ATTEMPT';
export const FETCH_RECIPES_SUCCESS = 'data::FETCH_RECIPES_SUCCESS';
export const FETCH_RECIPES_FAILED = 'data::FETCH_RECIPES_FAILED';
