
export const SELECT_INGREDIENT = 'ingredient::SELECT_INGREDIENT';
export const UNSELECT_ALL = 'ingredient::UNSELECT_ALL';

export const FETCH_INGREDIENTS_ATTEMPT = 'ingredient::FETCH_INGREDIENTS_ATTEMPT';
export const FETCH_INGREDIENTS_SUCCESS = 'ingredient::FETCH_INGREDIENTS_SUCCESS';
export const FETCH_INGREDIENTS_FAILED = 'ingredient::FETCH_INGREDIENTS_FAILED';

export const SELECT_CATEGORY_TYPE = 'recipe::SELECT_CATEGORY_TYPE';

export const FETCH_RECIPES_ATTEMPT = 'recipe::FETCH_RECIPES_ATTEMPT';
export const FETCH_RECIPES_SUCCESS = 'recipe::FETCH_RECIPES_SUCCESS';
export const FETCH_RECIPES_FAILED = 'recipe::FETCH_RECIPES_FAILED';
